// <auto-generated />
using AuthForge.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuthForge.Api.Data.Migrations.ConfigDb
{
    [DbContext(typeof(ConfigDbContext))]
    [Migration("20251113154800_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("AuthForge.Api.Entities.AppConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthForgeDomain")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseConnectionString")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DatabaseProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFromAddress")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailFromName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailProvider")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSetupComplete")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JwtSecretEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResendApiKeyEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordEncrypted")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SmtpUseSsl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("configurations", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
